# Employees Salaries Exploratory Data Analysis (EDA)

This project analyzes employee salary data to identify salary trends, job title patterns, and compensation insights using Python.

In [25]:
import pandas as pd
import numpy as np
pd.set_option('Display.max_columns',None)

In [ ]:
df = pd.read_csv('Salaries.csv')
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

## Display top 10 rows of the Dataset

In [27]:
# Task 1: Access the top 10 rows of the Dataset
# To access the top 10 Rows of dataset we use head() function
# other alternatives --> df.loc[],df.iloc[] and df[rowstart:rowend:step]
print('Top 10 Rows of the Dataset')
print('----------------------------')
df.head(10)

Top 10 Rows of the Dataset
----------------------------

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

## Check last 10 Rows of dataset

In [28]:
# Task 2: Access last 10 rows in the dataset
# To access last 10 rows we use tail() function
# other ways df.loc,df.iloc and df[len(df)-10]
print('Last 10 rows of the dataset')
print('--------------------------------')
df[len(df)-10:]

Last 10 rows of the dataset
--------------------------------

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148645,148646,Carolyn A Wilson,Human Services Technician,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148648,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

## Find number of rows and columns in the dataset

In [29]:
# Task 3: Find the number of rows and columns in the dataset
# To find number of rows and columns we use shape attribute
print('Total Number of rows and columns in the dataset')
print('-------------------------------------------------')
for rows,columns in [df.shape]:
    print('Number of rows =',rows)
    print('Number of columns =',columns)
print('-------------------------------------------------')

Total Number of rows and columns in the dataset
-------------------------------------------------
Number of rows = 148654
Number of columns = 13
-------------------------------------------------

## Get the information about dataset like total number of rows, total number of columns, datatypes of each columns and memory requirement

In [30]:
# Task 4: Find the number of rows/columns and data type of each column along with memory requirement
# To access the memory requirement,number rows/columns, non-null values we use a function info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

## Check null values in the Dataset

In [31]:
# Task 5: Display the number of null values in each column
# To get the number of null values in each column we can use isna() and isnull() functions
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

## Drop ID,Notes,Agency and status columns

In [32]:
# Task 6: Drop ID,Notes,Agency and status columns
# To remove the columns or rows we use drop() function 
# Hare axis=1 refers to the columns(axis=0 is for rows)
df = df.drop(['Id','Notes','Agency','Status'],axis=1)
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148650,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

## Get overall statistics in the dataframe

In [33]:
# Task 7: Get overall statistics in the dataframe
# To get the overall description of the data we use describe() function
df.describe(include='all')

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000
unique,110811,2159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,13,7036,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643
std,NaN,NaN,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538
min,NaN,NaN,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000
max,NaN,NaN,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

## Find the occurrence of the top 5 employee names

In [34]:
# Task 8: Find the occurences of first 5 employee names
# To obtain the number of repeat values in employeename we use head() and value_counts() functions
df['EmployeeName'].head().value_counts()

EmployeeName
NATHANIEL FORD       1
GARY JIMENEZ         1
ALBERT PARDINI       1
CHRISTOPHER CHONG    1
PATRICK GARDNER      1
Name: count, dtype: int64

## Find the number of unique job titles

In [35]:
# Task 9: Find the number of unique job tittles
# To know the number of unique value we use nunique() function 
# nunique() will give number of unique values
print('Number of unique job tittles =',df['JobTitle'].nunique())

Number of unique job tittles = 2159

## Find total number of job titles contain captain

In [36]:
# Task 10: Find total number of job tittles contain captain
# To obtain number of job titles containing captain 
# We should obtain the jobtitles with captain gives the series object
# lenth of the series will give the number of jobtitle with captain
captain = len(df[df['JobTitle'].str.contains('Captain')]['JobTitle'])
print('Number of titles containing Captain =',captain)

Number of titles containing Captain = 411

## Display all the employee names from fire department

In [37]:
# Task 11: Display all the employee names from fire department
# To obtain EmoployeeName from Firedepartment 
# Obtain the rows with of jobtitle with fire department then access the employeenames
print('Employees belongs to Fire Department')
print('----------------------------------------------------------')
df[df['JobTitle'].str.contains('FIRE DEPARTMENT')]['EmployeeName']

Employees belongs to Fire Department
----------------------------------------------------------

4           PATRICK GARDNER
6                 ALSON LEE
8            MICHAEL MORRIS
9        JOANNE HAYES-WHITE
10            ARTHUR KENNEY
                ...
4955              AUDRY LEE
5498          VINCENT PEREZ
8436          JENSEN RHODES
16285       AARON STEVENSON
32623          JAMES BARDEN
Name: EmployeeName, Length: 222, dtype: object

## Find minimum,maximum,average Base pay

In [38]:
# Task 12: Find minimum,maximum,average Base pay
# To know the min, mean and max values of BasePay
# We use agg() function 
print('Minimum,Maximum and Average values of BasePay')
print('--------------------------------------------------')
df['BasePay'].agg(['min','mean','max'])

Minimum,Maximum and Average values of BasePay
--------------------------------------------------

min       -166.01000
mean     66325.44884
max     319275.01000
Name: BasePay, dtype: float64

##  Data Cleaning

## Replace 'not provided' in employee name to NaN

In [39]:
# Task 13: Replace 'not provided' in employee name to NaN
# To replace 'not provided' with NaN we use replace() function
# To access those values use isna() or isnull()
df['EmployeeName'] = df['EmployeeName'].replace('Not provided',np.nan)
df[df['EmployeeName'].isna()]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
148646,NaN,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148650,NaN,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148651,NaN,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148652,NaN,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014

## Drop the rows having 5 missing values

In [40]:
# Task 14: Drop the rows having 5 missing values
# To drop the rows with 5 missing values first find the rows with 5 missing values
# Use drop() function to remove rows
ind = df[df.isnull().sum(axis=1) == 5].index
df = df.drop(ind)
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148645,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.0,0.00,0.00,2014
148647,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.0,0.00,0.00,2014
148648,Leon Walker,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

## Find the job title of Albert Pardini

In [41]:
# Task 15: Find the job tittle of Albert Pardini
# To know the job title of Albert Pardini using EmployeeName we can access the jobtitle column
# This gives series output then access the values in the series

print('Job title of Alber Pardini is',df[df['EmployeeName']=='Albert Pardini']['JobTitle'].values)

Job title of Alber Pardini is ['Captain 3']

## How much did Albert Pardini earn(Include benefits)

In [42]:
# Task 16: How much Albert Pardini make(Include benefits)
# To find the income of Albert Pardinin including benefits we should access the total benefits column
# this gives a series object using 'values' attribute you can get the TotalPayBenefits
print('Total income of Albert Pardini including benefits =',df[df['EmployeeName']=='Albert Pardini']['TotalPayBenefits'].values)

Total income of Albert Pardini including benefits = [253995.29]

## Display name of the person having highest base pay

In [43]:
# Task 17: Display name of the person having highest base pay
# To get the EmployeeName with highest BasePay we use max()
# Find the maximum of BasePay then access name of the Employee
print('Person with highest BasePay =',df[df['BasePay']==df['BasePay'].max()]['EmployeeName'].values)

Person with highest BasePay = ['Gregory P Suhr']

## Average base pay of all employees per year

In [44]:
# Task 18: Average base pay of all employees per year
# To obtain the average BasePay per year we should use groupby() function for Year column
# Use mean() function to obtain
print('Average BasePay per year')
print('----------------------------')
df2 = df.groupby('Year')
df2['BasePay'].mean()

Average BasePay per year
----------------------------

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

## Average base pay of employee per job title

In [45]:
# Task 19: Average base pay of employees per job title
# To obtain the average BasePay per year we should use groupby() function for jobtitle column
# Use mean() function to obtain
df3 = df.groupby('JobTitle')
df3['BasePay'].mean()

JobTitle
ACCOUNT CLERK                                     43300.806506
ACCOUNTANT                                        46643.172000
ACCOUNTANT INTERN                                 28732.663958
ACPO,JuvP, Juv Prob (SFERS)                       62290.780000
ACUPUNCTURIST                                     66374.400000
                                                      ...
X-RAY LABORATORY AIDE                             47664.773077
X-Ray Laboratory Aide                             46086.387100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    52609.910000
Youth Comm Advisor                                39077.957500
ZOO CURATOR                                       43148.000000
Name: BasePay, Length: 2158, dtype: float64

## Average base pay of employee having job title Accountant

In [46]:
# Task 20: Average base pay of employees having job title Accountant
# To obtain the BasePay of the employee with jobtitle Accountant
# Access the employees with jobtitle accountant then access their BasePay and use mean() function to obtain average
df[df['JobTitle'].str.contains('Accountant')]['BasePay'].mean()

np.float64(75336.18288798921)

## Find top 5 most common jobs

In [47]:
# Task 21: Find top 5 most common jobs
# To obtain the top 5 most repeated job titles
# Use the value_counts() function and head() function for JobTitle 
df['JobTitle'].value_counts().head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

## Conclusion

In this project, I performed Exploratory Data Analysis on employee salary data using Python and Pandas. I explored salary distributions, analyzed job titles, handled missing values, and derived insights related to employee compensation and departmental trends.